3 Migrate output callbacks to hooks
ucl-isd/moodle-local_examguard pull request #4
Opened 2024-07-04 09:21 UTC by leonstr

Migrate before_standard_top_of_body_html() to a hook for Moodle 4.4 (see MDL-81144).

Proposed fix for issue #3 . For this the plugin would require Moodle 4.4 or later.

2024-07-04 11:41 UTC, aydevworks requested changes
I think the code is fine, just a few warnings in the GHA results. @leonstr Could you please have a look? Thanks!
e.g. https://github.com/ucl-isd/moodle-local_examguard/actions/runs/9791801971/job/27041378745

2024-07-04 11:41 UTC, aydevworks commented on db/hooks.php
> +
Looks like missing `defined('MOODLE_INTERNAL') || die();`

2024-07-04 12:00 UTC, leonstr commented
@aydevworks Thanks for the feedback, I've added fixes for these warnings. Can you squash this into the original commit? Or let me know if you want me to submit a new PR.

2024-07-04 13:02 UTC, aspark21 commented
Don’t worry about it, I’ll squash when merging once we finalise 4.4 being prod ready

2024-07-13 20:27 UTC, aspark21 approved these changes

2024-07-13 20:27 UTC, merged